--CLCMSSQL01, HDICMS4, HDILOAD01, HDIQUERY02, HDIQUERY03, HDIRPT01, LVCMSD01, LVCMSD02 & VMLVPNT01
SELECT 
@@SERVERNAME
,@@SERVICENAME
,@@VERSION
,@@OPTIONS
,@@REMSERVER

SP_CONFIGURE 'show advanced options', 1
go
reconfigure
go
sp_configure